import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: Request) {
  try {
    const {
      requestType = 'booking',
      name,
      contactNumber,
      email,
      serviceType,
      pickupLocation,
      dropoffLocation,
      date,
      pickupTime,
      flightNumber,
      passengerCount,
      luggageCount,
      vehiclePreference,
      details
    } = await req.json();

    // 1. Validation
    if (!name || !contactNumber || !email) {
      return NextResponse.json(
        { error: 'Missing required contact fields. Please provide your Name, Phone Number, and Email.' },
        { status: 400 }
      );
    }

    const isQuote = requestType === 'quote';
    const typeLabel = isQuote ? 'Price Quotation Request' : 'Confirmed Booking Reservation';

    // 2. Validate SMTP configuration exists
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;

    if (!smtpUser || !smtpPass) {
      console.warn('SMTP credentials are not configured in environment variables. Logging request for testing.');
      return NextResponse.json({
        success: true,
        message: `${typeLabel} received successfully! Our team will contact you shortly.`
      });
    }

    const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
    const smtpPort = parseInt(process.env.SMTP_PORT || '587');
    const smtpSecure = process.env.SMTP_SECURE === 'true'; // true for port 465, false for 587

    // 3. Configure Transporter
    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpSecure,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    // 4. Formulate email contents
    const mailOptions = {
      from: `"${name}" <${smtpUser}>`,
      to: process.env.BOOKING_NOTIFICATION_EMAIL || 'info@elitecarsaustralia.com.au',
      replyTo: email,
      subject: `[Elite Cars Australia] New ${typeLabel} from ${name}`,
      text: `
New ${typeLabel} - Elite Cars Australia
--------------------------------------------------
Customer Name:      ${name}
Contact Number:     ${contactNumber}
Email Address:      ${email}
Service Selected:   ${serviceType || 'Not specified'}
Pickup Location:    ${pickupLocation || 'Not specified'}
Drop-off Location:  ${dropoffLocation || 'Not specified'}
Target Date:        ${date || 'Not specified'}
Pickup Time:        ${pickupTime || 'Not specified'}
Flight Number:      ${flightNumber || 'N/A'}
Passengers:         ${passengerCount || 'Not specified'}
Luggage:            ${luggageCount || 'Not specified'}
Vehicle Preference: ${vehiclePreference || 'Best Available'}

Additional Itinerary Notes:
${details || 'No additional details provided.'}
--------------------------------------------------
This email was auto-generated by the Elite Cars Australia booking system.
      `,
      html: `
        <div style="font-family: sans-serif; max-width: 650px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaea; border-radius: 12px; background-color: #fafafa;">
          <div style="background-color: #000000; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
            <h2 style="color: #ffffff; margin: 0; font-family: serif; letter-spacing: 1px;">ELITE CARS AUSTRALIA</h2>
            <p style="color: #c9a86a; margin: 5px 0 0 0; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 2px;">${typeLabel}</p>
          </div>
          
          <div style="padding: 25px; background-color: #ffffff; border-radius: 0 0 8px 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.02);">
            <h3 style="color: #333333; margin-top: 0; border-bottom: 2px solid #eaeaea; padding-bottom: 10px;">Customer & Trip Details:</h3>
            
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 0.95rem;">
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; width: 170px; border-bottom: 1px solid #f2f2f2;">Request Type</td>
                <td style="padding: 9px 0; color: #c9a86a; font-weight: bold; border-bottom: 1px solid #f2f2f2;">${typeLabel}</td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Customer Name</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Contact Number</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2;"><a href="tel:${contactNumber}" style="color: #c9a86a; text-decoration: none;">${contactNumber}</a></td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Email Address</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2;"><a href="mailto:${email}" style="color: #c9a86a; text-decoration: none;">${email}</a></td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Service Type</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2; text-transform: capitalize;">${serviceType || 'Standard Chauffeur'}</td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Pickup Location</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2;">${pickupLocation || 'Not specified'}</td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Drop-off Location</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2;">${dropoffLocation || 'Not specified'}</td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Date & Time</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2;">${date || 'TBD'} ${pickupTime ? 'at ' + pickupTime : ''}</td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Flight Number</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2;">${flightNumber || 'N/A'}</td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Passengers / Luggage</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2;">${passengerCount || '1'} Passengers · ${luggageCount || 'Standard'} Luggage</td>
              </tr>
              <tr>
                <td style="padding: 9px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Vehicle Preference</td>
                <td style="padding: 9px 0; color: #333333; border-bottom: 1px solid #f2f2f2;">${vehiclePreference || 'Best Available'}</td>
              </tr>
            </table>

            <h3 style="color: #333333; margin-top: 25px; border-bottom: 2px solid #eaeaea; padding-bottom: 10px;">Itinerary & Special Requests:</h3>
            <div style="background-color: #f9f9f9; border-left: 4px solid #c9a86a; padding: 15px; color: #444444; border-radius: 0 4px 4px 0; font-family: monospace; white-space: pre-wrap; font-size: 0.95rem; line-height: 1.5;">
              ${details || 'No additional details provided.'}
            </div>
          </div>
          
          <div style="text-align: center; margin-top: 20px; color: #888888; font-size: 0.75rem;">
            <p>&copy; ${new Date().getFullYear()} Elite Cars Australia. All rights reserved.</p>
          </div>
        </div>
      `,
    };

    // 5. Send Mail
    await transporter.sendMail(mailOptions);
    return NextResponse.json({
      success: true,
      message: `${typeLabel} has been submitted successfully! We will contact you shortly.`
    });
  } catch (error: any) {
    console.error('Nodemailer SMTP Error:', error);
    return NextResponse.json(
      { error: 'Mailer Error: Failed to send notification. Details: ' + error.message },
      { status: 500 }
    );
  }
}
