import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: Request) {
  try {
    const { name, contactNumber, email, serviceType, date, details } = await req.json();

    // 1. Validation
    if (!name || !contactNumber || !email || !serviceType || !date) {
      return NextResponse.json(
        { error: 'Missing required booking fields. Please check name, contact, email, service, and date.' },
        { status: 400 }
      );
    }

    // 2. Validate SMTP configuration exists
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;

    if (!smtpUser || !smtpPass) {
      console.error('SMTP credentials are not configured in environment variables.');
      return NextResponse.json(
        { error: 'SMTP Mailer is not configured on the server. Please add SMTP_USER and SMTP_PASS to your .env.local file.' },
        { status: 500 }
      );
    }

    const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
    const smtpPort = parseInt(process.env.SMTP_PORT || '587');
    const smtpSecure = process.env.SMTP_SECURE === 'true'; // true for port 465, false for 587

    // 3. Configure Transporter
    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpSecure,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    // 4. Formulate email contents
    const mailOptions = {
      from: `"${name}" <${smtpUser}>`, // Must be smtpUser to avoid spoofing rejections by mail providers
      to: 'zakkiullahbaig580@gmail.com',
      replyTo: email, // Direct replies back to the customer's email
      subject: `[My Corporate Cars] New Ride Booking Request from ${name}`,
      text: `
New Chauffeur Booking Request
--------------------------------------------------
Customer Name:    ${name}
Contact Number:   ${contactNumber}
Email Address:    ${email}
Service Selected: ${serviceType}
Target Date:      ${date}

Additional Details:
${details || 'No additional details provided.'}
--------------------------------------------------
This email was auto-generated by the My Corporate Cars booking system.
      `,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaea; border-radius: 12px; background-color: #fafafa;">
          <div style="background-color: #000000; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
            <h2 style="color: #ffffff; margin: 0; font-family: serif; letter-spacing: 1px;">MY CORPORATE CARS</h2>
            <p style="color: #ff3b30; margin: 5px 0 0 0; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 2px;">Premium Chauffeur Booking</p>
          </div>
          
          <div style="padding: 25px; background-color: #ffffff; border-radius: 0 0 8px 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.02);">
            <h3 style="color: #333333; margin-top: 0; border-bottom: 2px solid #eaeaea; padding-bottom: 10px;">Booking details:</h3>
            
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
              <tr>
                <td style="padding: 10px 0; color: #666666; font-weight: bold; width: 150px; border-bottom: 1px solid #f2f2f2;">Customer Name</td>
                <td style="padding: 10px 0; color: #333333; border-bottom: 1px solid #f2f2f2;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Contact Number</td>
                <td style="padding: 10px 0; color: #333333; border-bottom: 1px solid #f2f2f2;"><a href="tel:${contactNumber}" style="color: #ff3b30; text-decoration: none;">${contactNumber}</a></td>
              </tr>
              <tr>
                <td style="padding: 10px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Email Address</td>
                <td style="padding: 10px 0; color: #333333; border-bottom: 1px solid #f2f2f2;"><a href="mailto:${email}" style="color: #ff3b30; text-decoration: none;">${email}</a></td>
              </tr>
              <tr>
                <td style="padding: 10px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Service Type</td>
                <td style="padding: 10px 0; color: #333333; border-bottom: 1px solid #f2f2f2; text-transform: capitalize;">${serviceType}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0; color: #666666; font-weight: bold; border-bottom: 1px solid #f2f2f2;">Date Required</td>
                <td style="padding: 10px 0; color: #333333; border-bottom: 1px solid #f2f2f2;">${date}</td>
              </tr>
            </table>

            <h3 style="color: #333333; margin-top: 25px; border-bottom: 2px solid #eaeaea; padding-bottom: 10px;">Travel & Booking Notes:</h3>
            <div style="background-color: #f9f9f9; border-left: 4px solid #ff3b30; padding: 15px; color: #444444; border-radius: 0 4px 4px 0; font-family: monospace; white-space: pre-wrap; font-size: 0.95rem; line-height: 1.5;">
              ${details || 'No additional details provided.'}
            </div>
          </div>
          
          <div style="text-align: center; margin-top: 20px; color: #888888; font-size: 0.75rem;">
            <p>&copy; ${new Date().getFullYear()} My Corporate Cars. All rights reserved.</p>
          </div>
        </div>
      `,
    };

    // 5. Send Mail
    await transporter.sendMail(mailOptions);
    return NextResponse.json({ success: true, message: 'Your premium booking request has been sent successfully!' });
  } catch (error: any) {
    console.error('Nodemailer SMTP Error:', error);
    return NextResponse.json(
      { error: 'Mailer Error: Failed to send mail. Details: ' + error.message },
      { status: 500 }
    );
  }
}
